**A Pandas is Powerful py library used for data manipulation, analysis, and preprocessing.**

It Provide Data Structure
*   Series
*   Data Frame

✅ Why use Pandas?

* Handles structured data (CSV, Excel, SQL, JSON, etc.)
* Powerful data cleaning and transformation tools
* Efficient operations on large datasets
* Works well with NumPy and Matplotlib
* Used in real-world data science applications

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [4]:
import numpy as np
import pandas as pd
#Series(1D DS)
data = pd.Series([1,2,3,4,5])
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
s1 = pd.Series([1,2,3,np.nan,5])
s1

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64

In [17]:
s2 = pd.Series([1,2,3],index = ["aryan", "Shivam", "Heeml" ])
s2

aryan     1
Shivam    2
Heeml     3
dtype: int64

In [ ]:
scaler = 8

s4 = pd.Series(scaler, index=["apple","manog"])
s4

apple    8
manog    8
dtype: int64

In [3]:
#Accessing Element
np1 = np.random.randint(1,10,6)
np1
s1 = pd.Series(np1, index=[12,13,14 ,18, 45,55])
s1

NameError: name 'np' is not defined

In [ ]:
#indexing
s1[13] #here we get element by label not exact index value

np.int64(8)

In [ ]:
#Slicing
print(s1[2:5])#slicing was done by indexing

14    3
18    8
45    5
dtype: int64

In [ ]:
#if series have label in character then slicing work on label

In [ ]:
data = np.random.randint(1,20,20)

In [ ]:
#Filter the element
s1[s1 > 5]

13    8
18    8
55    6
dtype: int64

In [ ]:
s1[s1%2==0]

13    8
18    8
55    6
dtype: int64

In [ ]:
s1[(s1%2==0) & (s1>5)]

13    8
18    8
55    6
dtype: int64

In [9]:
print(s1.isnull().sum())#this give count of value is null

1

In [7]:
print(s1.isnull())#this give series of of boolean value where value is null

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [11]:
s5 = s1.dropna()#this makes new array, and drop null value, but previous array remain same
s5

0    1.0
1    2.0
2    3.0
4    5.0
dtype: float64

In [12]:
s1

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64

In [13]:
s1.dropna(inplace=True)#this remove nan elemnt from orginal array
s1

0    1.0
1    2.0
2    3.0
4    5.0
dtype: float64

In [14]:
l = s1.tolist()
l

[1.0, 2.0, 3.0, 5.0]

In [19]:
s2
dic = s2.to_dict()
dic

{'aryan': 1, 'Shivam': 2, 'Heeml': 3}

In [20]:
#dict to series
dictToSeri = pd.Series(dic)
dictToSeri

aryan     1
Shivam    2
Heeml     3
dtype: int64

In [ ]:
#2.Data Frame (same as 2d array but in labelled or n numbers of list)
data = {
    "Name":["Shivam", "Sani", "kajal"],
    "age":[20,21,23],
    "city":["Mumbai", "ahemdabad","Lucknow"]
}
datPanda = pd.DataFrame(data) #in this all col be there in all
datPanda

     Name  age       city
0  Shivam   20     Mumbai
1    Sani   21  ahemdabad
2   kajal   23    Lucknow

In [ ]:
data = {
    "A":[1,2,3],
    "B":[4,5,6]
}
dataFrm = pd.DataFrame(data)
dataFrm

   A  B
0  1  4
1  2  5
2  3  6

In [22]:
data = [
    [1,"alice",25],
     [2,"bob",30],
      [3,"charlie",35]
    ]

In [32]:
df = pd.DataFrame(data,columns=["ID", "Name", "Age"])
df

   ID     Name  Age
0   1    alice   25
1   2      bob   30
2   3  charlie   35

In [33]:
df["Name"] #get value by using col

0      alice
1        bob
2    charlie
Name: Name, dtype: object

In [34]:
df["Name"][0] #getting single item

'alice'

In [35]:
s = df["Name"]
s
s[0]

'alice'

In [36]:
df.iloc[0]#index based loc

ID          1
Name    alice
Age        25
Name: 0, dtype: object

In [38]:
df.loc[0] #in loc you can give index, as wll label
df2 = df.set_index("Name") #here setting the index as Name
df2

         ID  Age
Name
alice     1   25
bob       2   30
charlie   3   35

In [45]:
df2.loc[["alice", "charlie", "bob"]]
df2

         ID  Age
Name
alice     1   25
bob       2   30
charlie   3   35

In [51]:
df2.loc["alice":"bob"] #slicing
df2

         ID  Age
Name
alice     1   25
bob       2   30
charlie   3   35

In [52]:
df2.loc[df2["Age"] != 25]#this will

         ID  Age
Name
bob       2   30
charlie   3   35

In [54]:
df2["Age"].loc[df2["Age"] != 25] #this will return only Age col and label

Name
bob        30
charlie    35
Name: Age, dtype: int64

In [ ]:
df = pd.read_csv("/content/student_attendance_sheet.csv")
df

                           Topic  Unnamed: 1
0                           Date         NaN
1                   Student Name         NaN
2           bhupendrasinh Dodiya         NaN
3            Gulam Mohiyudin Tai         NaN
4               HITAKSHI GOSWAMI         NaN
5              Mohammadjuber Tai         NaN
6                   Tirth wadkar         NaN
7                   KHUSHI PATEL         NaN
8                  JUHED MULTANI         NaN
9                    MOHIT SINGH         NaN
10                  YUVRAJ TIMBA         NaN
11          Mohammadowais Ansari         NaN
12       MOHAMMADZED Mohammadzed         NaN
13                   ARYAN RAVAL         NaN
14              MAHAMMADAYAN TAI         NaN
15             MOHAMMADARMAN TAI         NaN
16                   JINAY PATEL         NaN
17               JAINAM SATHWARA         NaN
18               KAUSHIKABA ZALA         NaN
19  KISHAN GORVADIYA (Prajapati)         NaN
20                   DHRUV PATEL         NaN
21                    PARAM SHAH         NaN
22              ARSHIL GONDALIYA         NaN
23                  Mokshil shah         NaN

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

ACCESS DATA IN **[PANDAS](https://)**

In [ ]:
#df = pd.read_excel("")#here excel file path
df.loc[3] #access the particular column by index
df.iloc[3] #accss by position

Topic         Gulam Mohiyudin Tai
Unnamed: 1                    NaN
Name: 3, dtype: object

In [ ]:
#Filter Data
import numpy as np
import pandas as pd
data = np.random.randint(1,20,(3,3))
data

array([[ 2,  6,  2],
       [ 7, 18,  4],
       [ 7,  6, 11]])

In [ ]:
df = pd.DataFrame(data, columns=["num1","num2","num3"])

In [ ]:
df

   num1  num2  num3
0     2     6     2
1     7    18     4
2     7     6    11

In [ ]:
df["num1"]

0    2
1    7
2    7
Name: num1, dtype: int64

In [ ]:
df[df["num1"] > 5] #select row where element > 5

   num1  num2  num3
1     7    18     4
2     7     6    11

In [ ]:
print(df.shape)      # Get number of rows & columns
print(df.info())     # Summary of DataFrame
print(df.describe()) # Statistical summary of numeric columns
print(df.columns)    # List of column names
print(df.dtypes)     # Data types of each column

(3, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   num1    3 non-null      int64
 1   num2    3 non-null      int64
 2   num3    3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes
None
           num1       num2       num3
count  3.000000   3.000000   3.000000
mean   5.333333  10.000000   5.666667
std    2.886751   6.928203   4.725816
min    2.000000   6.000000   2.000000
25%    4.500000   6.000000   3.000000
50%    7.000000   6.000000   4.000000
75%    7.000000  12.000000   7.500000
max    7.000000  18.000000  11.000000
Index(['num1', 'num2', 'num3'], dtype='object')
num1    int64
num2    int64
num3    int64
dtype: object

**Modifying a DataFrame**

In [ ]:
#1.Adding a New Column
df["Salary"] = [50000, 60000, 70000]
df

   num1  num2  num3  Salary
0     2     6     2   50000
1     7    18     4   60000
2     7     6    11   70000

In [ ]:
#2.update the col
df["Salary"] = df["Salary"] + 5000 #increase all salary by 5k

In [ ]:
df

   num1  num2  num3  Salary
0     2     6     2   55000
1     7    18     4   65000
2     7     6    11   75000

In [ ]:
#3rd Drop col
df = df.drop(columns=["num3"])

In [ ]:
#4th Renaming Columns
df = df.rename(columns={"num1":"numbersOne"})

In [ ]:
df

   numbersOne  num2  Salary
0           2     6   55000
1           7    18   65000
2           7     6   75000

**Sorting & Filtering Data**

In [ ]:
df = df.sort_values("Salary", ascending=False)
df

   numbersOne  num2  Salary
2           7     6   75000
1           7    18   65000
0           2     6   55000

In [ ]:
df = df.sort_values("Salary", ascending=True)
df

   numbersOne  num2  Salary
0           2     6   55000
1           7    18   65000
2           7     6   75000

In [ ]:
#Filtering the Rows
filtered_rows = df[df["Salary"] > 60000]
filtered_rows

   numbersOne  num2  Salary
1           7    18   65000
2           7     6   75000

In [ ]:
df

   numbersOne  num2  Salary
0           2     6   55000
1           7    18   65000
2           7     6   75000

**Handling Missing Data**

In [ ]:
print(df.isnull().sum())#counting missing value in each col

numbersOne    0
num2          0
Salary        0
dtype: int64

In [ ]:
#Filling Missing Values
df.fillna("Unknown", inplace=True) # Replace NaN with unknown

In [ ]:
df.dropna(inplace=True)#dropping missing value