In [1]:
import numpy as np
import pandas as pd

**Re_Indexing & Altering Labels**

In [2]:
data = {
    'Name':['Alice', 'Bob', 'Charlie'],
    'Age':[25, 30, 35],
}
data

{'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}

In [19]:
df = pd.DataFrame(data,index=['a', 'b', 'c'])
df

      Name  Age
a    Alice   25
b      Bob   30
c  Charlie   35

In [7]:
df.reindex(['c', 'a', 'b'])#this show the data in our ouder wise by label

      Name  Age
c  Charlie   35
a    Alice   25
b      Bob   30

In [12]:
df.reindex(['c','a','b','p'])
#this makes the extra index

      Name   Age
c  Charlie  35.0
a    Alice  25.0
b      Bob  30.0
p      NaN   NaN

In [15]:
df = df.reindex(columns=['Age', 'Name'])
df
#this makes the column
#we can also rearrage the column
#if i make inplace=True

   Age     Name
a   25    Alice
b   30      Bob
c   35  Charlie

In [13]:
df

      Name  Age
a    Alice   25
b      Bob   30
c  Charlie   35

In [17]:
#Rename index and columns
df.rename(index={'a':'b'}, columns={'Name':'First Name'}, inplace=True)
df

   Age First Name
b   25      Alice
b   30        Bob
c   35    Charlie

In [18]:
df

   Age First Name
b   25      Alice
b   30        Bob
c   35    Charlie

In [20]:
df

      Name  Age
a    Alice   25
b      Bob   30
c  Charlie   35

In [21]:
#Directly Replace Index or column Labels
df.index = ['X','Y','Z']
df.columns = ['PersonName','PersonAge']
df

  PersonName  PersonAge
X      Alice         25
Y        Bob         30
Z    Charlie         35

In [22]:
df

  PersonName  PersonAge
X      Alice         25
Y        Bob         30
Z    Charlie         35

In [24]:
df.index

Index(['X', 'Y', 'Z'], dtype='object')

In [25]:
df.columns

Index(['PersonName', 'PersonAge'], dtype='object')

In [26]:
df.reset_index(inplace=True)#indx made with numerical start from 0

In [27]:
df

  index PersonName  PersonAge
0     X      Alice         25
1     Y        Bob         30
2     Z    Charlie         35

In [29]:
df.drop(columns=['index'], inplace=True)

In [30]:
df

  PersonName  PersonAge
0      Alice         25
1        Bob         30
2    Charlie         35

**Pivoting** :summary

In [32]:
# To perform pivoting in python
# i.pivot
# ii.pivot_table(add Aggregation func)
data = {
    "Date":["2024-01-01", "2024-01-01", "2024-01-02", "2024-01-02"],
    "Product":["Laptop", "Phone", "Laptop", "Phone"],
    "Sales":[1000, 500, 1500, 800]
}

df = pd.DataFrame(data)
df

         Date Product  Sales
0  2024-01-01  Laptop   1000
1  2024-01-01   Phone    500
2  2024-01-02  Laptop   1500
3  2024-01-02   Phone    800

In [33]:
df.pivot(index='Date', columns="Product", values="Sales")
#we get product in Column and

Product     Laptop  Phone
Date
2024-01-01    1000    500
2024-01-02    1500    800