# Pandas

In [6]:
import numpy as np
import sys
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/apple/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/apple/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python3.13 -m pip install --upgrade pip

In [7]:
import pandas as pd

#### pandas is a powerful Python library used for data manipulation, analysis, and preprocessing. It provides data structures like Series and DataFrame to work efficiently with structured data, making it a key tool in Data Science & Machine Learning.
#### ✅ Why use Pandas?
#### •Handles structured data (CSV, Excel, SQL, JSON, etc.)
#### •Powerful data cleaning and transformation tools
#### •Efficient operations on large datasets
#### •Works well with NumPy and Matplotlib
#### •Used in real-world data science applications

##### Installation pip install pandas
##### import pandas as pd

In [10]:
#pandas Data Structure
#1. Series Data Strucutre
data = pd.Series([10,20,30,40,50])
data

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [11]:
#each element has an INdex(0,1,2,3...)
#support custom indexing (e.g. index=['a','b','c'])

In [12]:
#Data Frame(2D Data Structure)
#A DataFrame is a table-like Structure(like an Excel Sheet).It consist of row and Column

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Tokyo"]
})
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Tokyo

In [13]:
#From a Dictionary
data = {
     "A": [1, 2, 3],
     "B": [4, 5, 6]}
df = pd.DataFrame(data)
print(df)

   A  B
0  1  4
1  2  5
2  3  6

In [15]:
#From a list of Lists
data = [[1,"Alice",25], [2,"bob",30], [3,"charlie",35]]
df = pd.DataFrame(data)
df

   0        1   2
0  1    Alice  25
1  2      bob  30
2  3  charlie  35

In [17]:
#From CSV file 
df = pd.read_csv('/Users/Project/pythonSelf/pythonSelf/RevisedImp/DataAnalysis/sample_data.csv') #here we add the excel file
df

   ID     Name  Age      City
0   1    Alice   23  New York
1   2      Bob   25    London
2   3  Charlie   22     Paris
3   4    David   24    Berlin
4   5      Eva   26     Tokyo

In [20]:
import sys

!{sys.executable} -m pip install openpyxl
df = pd.read_excel('/Users/Project/pythonSelf/pythonSelf/RevisedImp/DataAnalysis/sample_data.xlsx')
df

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python3.13 -m pip install --upgrade pip

   ID     Name  Age      City
0   1    Alice   23  New York
1   2      Bob   25    London
2   3  Charlie   22     Paris
3   4    David   24    Berlin
4   5      Eva   26     Tokyo

## Accessing Dat in Pandas

In [21]:
print(df["Name"])

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: str

In [22]:
print(df.Age)

0    23
1    25
2    22
3    24
4    26
Name: Age, dtype: int64

In [24]:
print(df.loc[1]) #Access row by label (index)
print(df.iloc[2]) #Access row by position

ID           2
Name       Bob
Age         25
City    London
Name: 1, dtype: object
ID            3
Name    Charlie
Age          22
City      Paris
Name: 2, dtype: object

In [25]:
print(df["Age"] > 25)

0    False
1    False
2    False
3    False
4     True
Name: Age, dtype: bool

In [31]:
print(df.shape) #get Number of row and Cols
print(df.info()) #summary of DataFrame
print(df.describe()) # Statistical summary of numeric columns
print(df.columns)
print(df.dtypes) #dataTypes each column

(5, 4)
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      5 non-null      int64
 1   Name    5 non-null      str
 2   Age     5 non-null      int64
 3   City    5 non-null      str
dtypes: int64(2), str(2)
memory usage: 292.0 bytes
None
             ID        Age
count  5.000000   5.000000
mean   3.000000  24.000000
std    1.581139   1.581139
min    1.000000  22.000000
25%    2.000000  23.000000
50%    3.000000  24.000000
75%    4.000000  25.000000
max    5.000000  26.000000
Index(['ID', 'Name', 'Age', 'City'], dtype='str')
ID      int64
Name      str
Age     int64
City      str
dtype: object

# Modifying a DataFrame

In [36]:

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Tokyo"]
})

df["Salary"] = [50000, 60000, 70000] #Adding extra Column
df["Age"] = df["Age"] + 1 #updating Age
df = df.drop(columns=["City"]) #dropping the column
df = df.rename(columns={"Name":"Full Name"}) #Renaming the column

df

  Full Name  Age  Salary
0     Alice   26   50000
1       Bob   31   60000
2   Charlie   36   70000

# Sorting & Filtering Data

In [37]:
df = df.sort_values("Age", ascending=False)
print(df)

  Full Name  Age  Salary
2   Charlie   36   70000
1       Bob   31   60000
0     Alice   26   50000

In [38]:
filtered_df = df[df["Age"] > 28]
filtered_df

  Full Name  Age  Salary
2   Charlie   36   70000
1       Bob   31   60000

# Handling Missing Data

In [39]:
print(df.isnull().sum()) #count missing Values in Each Column

Full Name    0
Age          0
Salary       0
dtype: int64

In [40]:
df.fillna("Unknown", inplace=True) # Replace NaN with 'Unkown'

  Full Name  Age  Salary
2   Charlie   36   70000
1       Bob   31   60000
0     Alice   26   50000

In [42]:
df.dropna(inplace=True)#Drop row with missing value
df

  Full Name  Age  Salary
2   Charlie   36   70000
1       Bob   31   60000
0     Alice   26   50000

# Aggregation & Grouping

In [43]:
print(df["Age"].mean()) #Average age

31.0

In [44]:
print(df["Age"].sum()) #Sum of all ages

93

In [47]:
grouped = df.groupby("Full Name")["Age"].mean()
grouped

Full Name
Alice      26.0
Bob        31.0
Charlie    36.0
Name: Age, dtype: float64

# Merging, Joining, and Concatenation

In [48]:
df1 = pd.DataFrame({"ID": [1,2,3], "Name": ["A", "B", "C"]})
df2 = pd.DataFrame({"ID": [1,2,3], "Salary": [1000, 2000, 3000]})

merged_df = pd.merge(df1, df2, on="ID")
print(merged_df)

   ID Name  Salary
0   1    A    1000
1   2    B    2000
2   3    C    3000

In [49]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"A": [3, 4]})

concatenated = pd.concat([df1, df2])
print(concatenated)

   A
0  1
1  2
0  3
1  4